### ISSUE TITLE
Make the logging of messages to the console configurable

### ISSUE THREAD

**Issue by manuelbernhardt** [rleibman/scalajs-reconnecting-websocket#1]
It would be nice if the logging of messages to the JS console could be made optional via a constructor flag. Nice library btw!

**Comment by rleibman** [comment]
Thanks... I was about to start implementing this request, when I realized it's already implemented (the debug flag in the constructor), I hope this is what you want!

**Comment by rleibman** [comment]
However... you were right, it wasn't being consistently used, I just made that change and pushed a new version (1.1.1), enjoy, let me know if it works for you.

**Comment by manuelbernhardt** [comment]
@rleibman thanks!
